### ISSUE TITLE
Server generates 500 Internal Server Error

### ISSUE THREAD

**Issue by lsorba** [Swing-team/pendulums-web-client#121]
Dear pendulum team,

The server doesn't seem to work this morning, here is the error I am getting:

Web interface: 
![image](https://user-images.githubusercontent.com/5699257/227872190-a1e2b2b3-cba6-49d2-8794-38d703f83e04.png)

Request sent to the server
```
POST | https://app.pendulums.io/api/auth/signin
500 Internal Server Error
```

Could you please have a look?

Thank you in advance,

All the best,
Laurent.

Edit: fixed typo error

**Comment by mohammadrafigh** [comment]
Thanks for reporting. It's fixed now. @lsorba @krisraich

**Comment by lsorba** [comment]
Thank you for the fix. Somehow I lost the activities I logged this morning while being offline. There might be a sync issue :/

**Comment by mohammadrafigh** [comment]
Please try to press the sync button under the menu at left side, this may
fix your problem.

**Comment by lsorba** [comment]
Only the active activity remained, the past ones from the morning disappeared. Clicking on the sync button did not fix the problem. Not nice but also not a big deal, I remember what I did this morning. Thanks anyways!

**Comment by mohammadrafigh** [comment]
I'm so sorry for the inconvenience. Thanks for using Pendulums.
